#ブロック壊したときに飴ちゃん出る確率
#下記の場合だと1/70の確率になります

BlockLuckAmount: 70
BlockLuck: 1

#モブを倒したときに飴ちゃん出る確率
#下記の場合だと1/70の確率になります

MobLuckAmount: 70
MobLuck: 1

#ブロックを壊した時に出るアイテム名の設定(カラーコード使用可)

BlockDropItemName: "&5美味しい&6飴ちゃん"

#モブを倒した時に出るアイテム名の設定(カラーコード使用可)

MobDropItemName: "&5美味しい&6飴ちゃん"

#遊べるワールドの設定
#通常資源.資源ネザー.資源エンドに項目分けてあるのでワールド名をそれぞれ記入してください
normal: "save"
nether: "save"
end: "save"