#ブロック壊したときに飴ちゃん出る確率
#下記の場合だと1/70の確率になります
BlockLuckAmount: 70
BlockLuck: 1
#モブを倒したときに飴ちゃん出る確率
#下記の場合だと1/70の確率になります
MobLuckAmount: 70
MobLuck: 1
#ブロックを壊した時に出るアイテム名の設定(カラーコード使用可)
BlockBlockDropItemName: "&5美味しい&6飴ちゃん"
#モブを倒した時に出るアイテム名の設定(カラーコード使用可)
MobDropItemName: "&5美味しい&6飴ちゃん"