name: TheSlowHalloween
version: '1.0'
main: theslowhalloween.theslowhalloween.TheSlowHalloween
api-version: 1.17
authors: [46kuri_]
description: TSLplugin
depend: ["mcMMO"]

commands:
  tsh:
    description: リロードコマンド
    permission: TheSlowHalloween.permission.Member

permissions:
  TheSlowHalloween.permission.Admin:
    default: op
  TheSlowHalloween.permission.Member:
    default: true